// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"maxblog-me-main/internal/api"
	"maxblog-me-main/internal/conf"
	"maxblog-me-main/internal/core"
	"maxblog-me-main/internal/middleware/interceptor"
	"maxblog-me-main/src/handler"
	"maxblog-me-main/src/service"
)

// Injectors from wire.go:

func InitInjector() (*Injector, error) {
	bDemo := &service.BDemo{}
	logger := &core.Logger{}
	response := &core.Response{
		ILogger: logger,
	}
	hDemo := &handler.HDemo{
		BDemo: bDemo,
		IRes:  response,
	}
	apiHandler := &api.Handler{
		HandlerDemo: hDemo,
	}
	auth := &interceptor.Auth{
		ILogger: logger,
	}
	interceptorInterceptor := &interceptor.Interceptor{
		InterceptorAuth: auth,
	}
	engine := conf.InitGinEngine(apiHandler, interceptorInterceptor)
	injector := &Injector{
		Engine:      engine,
		Handler:     apiHandler,
		Interceptor: interceptorInterceptor,
	}
	return injector, nil
}
