run_mode: "release"
logger:
  color: false

app:
  app_name: "maxblog-me-main"
  version: "0.1.0"

server:
  host: "0.0.0.0"
  port: 9202
  protocol: "https"
  secure: true
  shutdown_timeout: 10
  tags:
    - maxblog-me-main
    - maxblog

upstream:
  maxblog_fe_main:
    host: "10.192.0.5"
    port: 9101

downstream:
  maxblog_be_demo:
    host: "10.192.0.5"
    port: 9304

redis:
  host: "127.0.0.1"
  port: 6379

consul:
  host: "127.0.0.1"
  port: 8500

